import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'flex-start',
        flexDirection: 'column',
        backgroundColor: '#FBFBFBFB',
        alignItems: 'center',
        color: 'black',
    },
    formContainer: {
        //flex: 1,
        justifyContent: 'flex-start',
        flexDirection: 'column',
        //height: "100%",
        //paddingBottom: 100,
        paddingTop: 50,
        alignItems: 'stretch',
        color: 'black',
    },
    formElement: {
        //paddingLeft: 40,
        //paddingRight: 40,
        paddingHorizontal: 20,
        paddingVertical: 10,
        color: 'black',
    },
    backgroundImage: {
        flex: 1,
        //width: '100%',
        //height: '100%',
        resizeMode: 'contain',
        justifyContent: 'flex-start',
    },
    titles: {
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
        justifyContent: 'center',
    },
    name: {
        //fontfamily: 'sans-serif',
        fontSize: 28,
        fontWeight: 'bold',
        color: 'black',
        textAlign: 'center',
        justifyContent: 'center',
        paddingBottom: 5,
    },
    text: {
        fontSize: 20,
        fontWeight: 'bold',
        color: 'black',
        textAlign: 'center',
        justifyContent: 'center',
        paddingBottom: 5,
        color: 'black',
    },
    tips: {
        fontSize: 20,
        fontWeight: 'bold',
        color: 'black',
        textAlign: 'left',
        justifyContent: 'center',
        paddingBottom: 5,
    },
    generalText: {
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: 18,
        margin: 10,
        color: 'black',
        textAlign: 'center',
    },
});
export default styles;