import {StyleSheet, Dimensions} from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'flex-start',
        flexDirection: 'column',
        backgroundColor: '#FBFBFB',
        alignItems: 'center',
        //backgroundColor: '#00FFFF',
    },
    answerBox: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#e6e6e6',
        height: 250,
        width: '95%',
        margin: 10,
        marginHorizontal: 50,
        padding: 25,
        borderRadius: 10,
        borderColor: 'red',
        borderWidth: 2,
        shadowOffset: { width: 4, height: 4 },
        shadowColor: 'black',
        shadowOpacity: 1,
        elevation: 4,
    },
    answerText: {
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: 20,
        margin: 25,
        color: 'black',
        textAlign: 'center',
    },
    backButton: {
        //flex: 1,
        borderRadius: 25,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        //marginTop: 30,
        //marginBottom: 30,
        width: '55%',
        //paddingHorizontal: 400,
        backgroundColor: '#FF0000',
        borderColor: 'white',
        borderWidth: 0.5,
        shadowOffset: { width: 10, height: 10 },
        shadowColor: 'black',
        shadowOpacity: 1,
        elevation: 8,
    },
    disclaimerTextBox: {
        flex: 1,
        justifyContent: 'flex-end',
        paddingVertical: 20,
        color: 'black',
        //marginTop: 15,
        //backgroundColor: '#00FFFF',
        //borderWidth: 0.5,
        //borderColor: 'blue',
    },
    disclaimerTitleText: {
        justifyContent: 'flex-start',
        alignItems: 'center',
        textAlign: 'left',
        marginHorizontal: 10, 
        paddingHorizontal: 10,  
        fontSize: 14, 
        fontWeight: 'bold',
        fontStyle: 'italic',
        color: 'black',
        //borderWidth: 0.5,
        //borderColor: 'blue',
        //textAlign: 'left',
    },
    disclaimerText: {
        marginHorizontal: 10, 
        paddingHorizontal: 10, 
        fontSize: 14, 
        fontStyle: 'italic',
        textAlign: 'left',
        color: 'black',
    },
    title: {
        fontSize: 15,
        fontWeight: 'bold',
        textAlign: 'center',
        justifyContent: 'center',
        paddingBottom: 8,
        
    },
    formElement: {
        //flex: 1,
        //paddingLeft: 40,
        //paddingRight: 40,
        paddingHorizontal: 0,
        paddingVertical: 0,
        marginVertical: 25,
        alignItems: 'center',
        
        //backgroundColor: '#000000',
        width: '100%',
        
    },

});

export default styles;