DROP TABLE IF EXISTS has CASCADE;
DROP TABLE IF EXISTS infected CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS potential_contact CASCADE;
DROP TABLE IF EXISTS statuses CASCADE;
DROP TABLE IF EXISTS virus CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP FUNCTION IF EXISTS notIFy_algorithm;

